<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Document' => 'Dokument hinzufügen',
    'Adress1' => 'Adresse',
    'Adress2' => 'Adresse',
    'Are you sure you want to delete this item?' => '',
    'Country' => 'Land',
    'Create' => '',
    'Create Letter' => '@@@@',
    'Create Sender' => '',
    'Create {modelClass}' => '{modelClass} anlegen',
    'Delete' => 'Löschen',
    'Documents' => 'Dokumente',
    'Download' => '',
    'Folder' => '',
    'Home' => '',
    'ID' => '',
    'Job' => 'test',
    'Letters' => '@@@@',
    'Message' => '',
    'Name' => '',
    'New Sender' => '@@@@',
    'Reset' => '',
    'Search' => '',
    'Sender' => 'Absender',
    'Senders' => 'Absender',
    'State' => '',
    'Time' => '',
    'Title' => '',
    'Town' => 'Ort',
    'Update' => 'Bearbeiten',
    'Update {modelClass}: ' => '{modelClass} bearbeiten',
    'Zip' => 'PLZ',
    'cancel' => '',
    'create' => '',
];
