<?php
/**
 * Created by PhpStorm.
 * User: Toni
 * Date: 13.03.2019
 * Time: 20:40
 */

namespace app\models\search;


use app\models\DocumentType;
use yii\data\ActiveDataProvider;

class DocumentTypeSearch extends DocumentType
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function search($params){
        $query = DocumentType::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
        ]);

        $query->andFilterWhere(['like', 'name', $this->name])
            ->andFilterWhere(['like', 'regex', $this->regex]);

        return $dataProvider;
    }
}