
#FROM php:5.6-apache
FROM php:7.2-apache

#install modules
RUN apt-get update && apt-get -y install \
        tesseract-ocr \
        tesseract-ocr-deu \
        tesseract-ocr-eng \
        imagemagick \
        poppler-utils \
        wget \
        git \
        zlib1g-dev \
        libpng-dev \
        libzip-dev
        
RUN docker-php-ext-install mbstring 
RUN docker-php-ext-install zip gd 
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql

#COPY ./install-composer.sh /var/www/html/

RUN cd /var/www/html \
    && wget -q https://getcomposer.org/composer.phar \
    && git clone https://github.com/toschqlb/letter-safe \
    && cd letter-safe \
    && php ../composer.phar install \
    && php ../composer.phar update

ENV LETTERSAFE_DB_SERVER db
ENV LETTERSAFE_DB_DB letter-safe
ENV LETTERSAFE_DB_USER letter-safe
ENV LETTERSAFE_DB_PASSWORD letter-safe

WORKDIR /var/www/html/letter-safe

RUN chmod 0777 /var/www/html/letter-safe/web/assets
RUN chmod -R 0777 /var/www/html/letter-safe/runtime

COPY entrypoint.sh /var/www/html/letter-safe/entrypoint.sh
RUN chmod 0777 /var/www/html/letter-safe/entrypoint.sh

COPY .files/000-default.conf /etc/apache2/sites-available/000-default.conf

CMD ["./entrypoint.sh"]
CMD ["apache2-foreground"]

EXPOSE 80/tcp

#ENTRYPOINT echo $LETTERSAFE_DB_SERVER
#ENTRYPOINT /var/www/html/letter-safe/entrypoint.sh
#CMD ["apache2-foreground
