FROM php:7.2-apache

#install software
RUN apt-get update && apt-get -y install \
        tesseract-ocr \
        tesseract-ocr-deu \
        tesseract-ocr-eng \
        imagemagick \
        poppler-utils \
        wget \
        git \
        zlib1g-dev \
        libpng-dev \
        libzip-dev \
        cron \
        libmagickwand-dev

#install PHP-Modules
RUN docker-php-ext-install \
        mbstring \
        zip \
        gd \
        mysqli \
        pdo \
        pdo_mysql \
&& pecl install imagick-3.4.3 \
&& docker-php-ext-enable imagick

#prepare letter-safe
RUN cd /var/www/html \
    && wget -q https://getcomposer.org/composer.phar \
    && git clone https://github.com/toschqlb/letter-safe \
    && cd letter-safe \
    && php ../composer.phar install \
    && php ../composer.phar update

ENV LETTERSAFE_DB_SERVER db
ENV LETTERSAFE_DB_DB letter-safe
ENV LETTERSAFE_DB_USER letter-safe
ENV LETTERSAFE_DB_PASSWORD letter-safe

WORKDIR /var/www/html/letter-safe

COPY entrypoint.sh /var/www/html/letter-safe/entrypoint.sh
COPY ./files/000-default.conf /etc/apache2/sites-available/000-default.conf

#Schreibrechte und Crontab
RUN chmod 0777 /var/www/html/letter-safe/web/assets \
&& chmod -R 0777 /var/www/html/letter-safe/runtime \
&& chmod -R 0777 /var/www/html/letter-safe/web/data \
&& chmod 0777 /var/www/html/letter-safe/entrypoint.sh \
&& echo "* *   * * *   root    php /var/www/html/letter-safe/yii queue/execute > /dev/null 2>&1 &" >> /etc/crontab

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 80/tcp
