<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Document' => 'Dokument hinzufügen',
    'Adress1' => 'Adresse',
    'Adress2' => 'Adresse',
    'Are you sure you want to delete this item?' => '',
    'Color' => 'Farbe',
    'Country' => 'Land',
    'Create' => 'Erstellen',
    'Create Letter' => '@@@@',
    'Create Sender' => 'Absender erstellen',
    'Create Tag' => 'Tag erstellen',
    'Create User' => 'Nutzer anlegen',
    'Create {modelClass}' => '{modelClass} anlegen',
    'Delete' => 'Löschen',
    'Document ID' => 'Dokument-id',
    'Document Type' => 'Dokumenttyp',
    'Document Type ID' => 'Dokumenttyp-id',
    'Documentanalyse' => 'Dokumentanalyse',
    'Documents' => 'Dokumente',
    'Download' => 'Downloas',
    'Email' => 'E-Mail',
    'Field ID' => 'Feld Id',
    'Folder' => 'Ordner',
    'Home' => 'Home',
    'ID' => 'ID',
    'Inbox' => 'Eingang',
    'Job' => 'test',
    'Letters' => '@@@@',
    'Loading...' => 'Laden...',
    'Logout' => 'Abmelden',
    'Message' => '@@@@',
    'Name' => 'Name',
    'New Sender' => '@@@@',
    'Password' => 'Passwort',
    'Passwords don\'t match' => 'Passwörter stimmen nicht überein',
    'Refreshing...' => 'Aktuallisiern',
    'Reset' => 'Zurücksetzten',
    'Search' => 'Suchen',
    'Sender' => 'Absender',
    'Sender documents' => 'Absender Dokumente',
    'Senders' => 'Absender',
    'State' => 'Status',
    'Tags' => 'Tags',
    'Time' => 'Uhrzeit',
    'Title' => 'Titel',
    'Town' => 'Ort',
    'Update' => 'Bearbeiten',
    'Update {modelClass}: ' => '{modelClass} bearbeiten',
    'User' => 'Nutzer',
    'Username' => 'Nutzername',
    'Users' => 'Nutzer',
    'Value' => 'Wert',
    'Zip' => 'PLZ',
    '_empty' => 'leer',
    'add' => 'hinzufügen',
    'cancel' => 'abbrechen',
    'create' => 'erstellen',
    'document details' => 'Dokumentdetails',
    'documents' => 'Dokumente',
    'documnet information' => 'Dokumentinformationen',
    'no documents found' => 'keine Dokumente gefunden',
    'no logo' => 'kein Logo',
    'please wait...' => 'bitte warten...',
    'search...' => 'suchen...',
    'searchresults' => 'Suchergebnisse',
    'senders' => 'Absender',
    'statistics' => 'Statistik',
    'view all documnets' => 'alle Dokumente anzeigen',
];
